//Get por page

export const GET_PAIS = 'GET_PAIS'
export const GET_PAIS_SUCCESS = 'GET_PAIS_SUCCESS'
export const GET_PAIS_FAILED = 'GET_PAIS_FAILED'

//Get por PROVINCIA

export const GET_PROVINCIA = 'GET_PROVINCIA'
export const GET_PROVINCIA_SUCCESS = 'GET_PROVINCIA_SUCCESS'
export const GET_PROVINCIA_FAILED = 'GET_PROVINCIA_FAILED'

//GET PAIS

export const GET_CIUDAD = 'GET_CIUDAD'
export const GET_CIUDAD_SUCCESS = 'GET_CIUDAD_SUCCES'
export const GET_CIUDAD_FAILED = 'GET_CIUDAD_FAILED'

//post

export const POST_USUARIO = 'POST_USUARIO'
export const POST_USUARIO_SUCCESS = 'POST_USUARIO_SUCCESS'
export const POST_USUARIO_FAILED = 'POST_USUARIO_FAILED'
