//Get por page

export const GET_HALLAZGOS = 'GET_HALLAZGOS'
export const GET_HALLAZGOS_SUCCESS = 'GET_HALLAZGOS_SUCCESS'
export const GET_HALLAZGOS_FAILED = 'GET_HALLAZGOS_FAILED'

//Get por generico

export const GET_GENERICO = 'GET_GENERICO'
export const GET_GENERICO_SUCCESS = 'GET_GENERICO_SUCCESS'
export const GET_GENERICO_FAILED = 'GET_GENERICO_FAILED'

//post hallazgos

export const POST_HALLAZGOS = 'POST_HALLAZGOS'
export const POST_HALLAZGOS_SUCCES = 'POST_HALLAZGOS_SUCCESS'
export const POST_HALLAZGOS_FAILED = 'POST_HALLAZGOS_FAILED'
